/**
 * @file    dice.h
 * @author  Stephen Papierski <stephenpapierski@gmail.com>
 * @date    28 February 2015
 * @version 0.1
 */
#ifndef DICE_H
#define DICE_H

//DEFINES
#define RANDOM_MAX  5   //define max number generated by rand()
#define LINE_DDR    DDRB
#define LINE_PORT   PORTB
#define LINE0       1<<PORTB0
#define LINE1       1<<PORTB1
#define LINE2       1<<PORTB4
#define LINE3       1<<PORTB3
#define PIEZO       1<<PORTB2

#define UL_LED_DDR  (LINE1 | LINE2)         //Upper Left LED DDR
#define UR_LED_DDR  (LINE0 | LINE1)         //Upper Right
#define ML_LED_DDR  (LINE1 | LINE2)         //Middle Left
#define MC_LED_DDR  (LINE2 | LINE3)         //Middle Center
#define MR_LED_DDR  (LINE0 | LINE3)         //Middle Right
#define BL_LED_DDR  (LINE2 | LINE3)         //Bottom Left
#define BR_LED_DDR  (LINE0 | LINE1)         //Bottom Right

#define UL_LED_PORT LINE2                   //Upper Left LED PORT
#define UR_LED_PORT LINE0                   //Upper Right
#define ML_LED_PORT LINE1                   //Middle Left
#define MC_LED_PORT LINE3                   //Middle Center
#define MR_LED_PORT LINE0                   //Middle Right
#define BL_LED_PORT LINE2                   //Bottom Left
#define BR_LED_PORT LINE1                   //Bottom Right


//led byte mask for led_state
#define UL_LED 0x01                   //Upper Left LED PORT
#define UR_LED 0x02                   //Upper Right
#define ML_LED 0x04                   //Middle Left
#define MC_LED 0x08                   //Middle Center
#define MR_LED 0x10                   //Middle Right
#define BL_LED 0x20                   //Bottom Left
#define BR_LED 0x40                   //Bottom Right

//dice faces
#define ONE     (MC_LED)
#define TWO     (UL_LED | BR_LED)
#define THREE   (UL_LED | MC_LED | BR_LED)
#define FOUR    (UL_LED | UR_LED | BL_LED | BR_LED)
#define FIVE    (UL_LED | UR_LED | MC_LED | BL_LED | BR_LED)
#define SIX     (UL_LED | UR_LED | ML_LED | MR_LED | BL_LED | BR_LED)

#define NUM_LEDS        7
#define ROLL_FACE_TIME  2000    //time each face will display while rolling
#define FACE_TIMEOUT    500000  //time number will displayed before leds turn off

//FUNCTIONS
int main(void);
void set_led(void);
unsigned char rand_face(void);

//VARIABLES
volatile unsigned int led_index;
volatile unsigned short roll_flag;
unsigned char led_state;
unsigned long int roll_time;
unsigned long int face_time; //how long current face has been displayed

//DDR direction setting for LEDs
const unsigned char led_ddr[7] = {
    UL_LED_DDR,
    UR_LED_DDR,
    ML_LED_DDR,
    MC_LED_DDR,
    MR_LED_DDR,
    BL_LED_DDR,
    BR_LED_DDR,
};

//PORT output setting for LEDs
const unsigned char led_port[7] = {
    UL_LED_PORT,
    UR_LED_PORT,
    ML_LED_PORT,
    MC_LED_PORT,
    MR_LED_PORT,
    BL_LED_PORT,
    BR_LED_PORT,
};

const unsigned char led_mask[7] = {
    UL_LED,
    UR_LED,
    ML_LED,
    MC_LED,
    MR_LED,
    BL_LED,
    BR_LED,
};


const unsigned char led_faces[6] = {
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX
};

#endif
